### ISSUE TITLE
Some devices crash 

### ISSUE THREAD

**Issue by metaine** [mesmotronic/air-ane-fullscreen#25]
Hello! We have application published at GooglePlay, and number of crash reports from users containing logs like this:

[ExceptionBacktrace] => java.lang.IllegalArgumentException
	at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
	at com.mesmotronic.ane.fullscreen.FullScreenContext$1.onWindowFocusChanged(FullScreenContext.java:114)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onWindowFocusChanged(PhoneWindow.java:2738)
	at android.view.View.dispatchWindowFocusChanged(View.java:7996)
	at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1001)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3516)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
	at dalvik.system.NativeStart.main(Native Method)

    [localizedModel] => LENOVO Lenovo B6000-H

Have any ideas? Thank you

**Comment by metaine** [comment]
ANE Fullscreen version 1.3.3, Adobe AIR SDK 19

**Comment by neilrackett** [comment]
Thanks for the info: we can probably implement a quick fix using `try...catch` for now.

I'll try to take a look later this week, so watch this space.

**Comment by neilrackett** [comment]
[Release v1.4.0](https://github.com/mesmotronic/air-ane-fullscreen/releases/tag/v1.4.0) should resolve this issue.

**Comment by metaine** [comment]
Thanks!

**Comment by metaine** [comment]
Hi! Looks like Adobe fixes several serious issues in AIR SDK (version 21 seems to be doing well) and I have Macbook now (so iOS build issue is not a problem). So now I can take 1.4.x to my app (to fix this  #25), but which version's better? Shoud I take latest (rolled back to AIR 19) or stick with 1.4.6?

**Comment by neilrackett** [comment]
Stick with 1.4.6, but if you have any issues let us know.

**Comment by metaine** [comment]
Thanks! I have one more question... 
We have set minSdkVersion = 17 for our app (and really expect it to run on 4.2 and higher) (no targetSdkVersion we set explicitly)
Fullscreen ANE targetSdkVersion is 23, how this will affect the main application targeting range?

**Comment by neilrackett** [comment]
The `minSdkVersion` for the ANE is 9, so it should have no affect whatsoever.
