### ISSUE TITLE
Crash on Nexus 7

### ISSUE THREAD

**Issue by LorenzGit** [mesmotronic/air-ane-fullscreen#26]
Hi, often I am getting crashes on Nexus 7 and other devices, this is the stack trace:
I am using the latest version of mesmotronic fullscreen.

`Android: 5.1.1
Manufacturer: asus
Model: Nexus 7
Date: Wed Jan 27 11:51:50 PST 2016

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
	at com.mesmotronic.ane.fullscreen.FullScreenContext.getWindow(FullScreenContext.java:91)
	at com.mesmotronic.ane.fullscreen.FullScreenContext.getDecorView(FullScreenContext.java:271)
	at com.mesmotronic.ane.fullscreen.FullScreenContext.setSystemUiVisibility(FullScreenContext.java:276)
	at com.mesmotronic.ane.fullscreen.functions.ImmersiveModeFunction$2.onSystemUiVisibilityChange(ImmersiveModeFunction.java:117)
	at android.view.View.dispatchSystemUiVisibilityChanged(View.java:18151)
	at android.view.ViewGroup.dispatchSystemUiVisibilityChanged(ViewGroup.java:1441)
	at android.view.ViewRootImpl.handleDispatchSystemUiVisibilityChanged(ViewRootImpl.java:5229)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3366)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

Also that issue might be causing this other crash:
`java.lang.IllegalArgumentException
	at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
	at com.mesmotronic.ane.fullscreen.FullScreenContext$1.onWindowFocusChanged(FullScreenContext.java:114)
	at com.mesmotronic.ane.fullscreen.functions.ImmersiveModeFunction$3.onWindowFocusChanged(ImmersiveModeFunction.java:136)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onWindowFocusChanged(PhoneWindow.java:2948)
	at android.view.View.dispatchWindowFocusChanged(View.java:8376)
	at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:978)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3721)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5653)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)`

**Comment by neilrackett** [comment]
I've implemented a quick fix for this issue that should prevent the crashes you've been experiencing: can you try release 1.4.1?
